def banner():
    print("\033[1;36m")    
    print("\n")
    print("    ██╗███████╗███████╗████████╗   ")
    print("    ██║██╔════╝██╔════╝╚══██╔══╝   ")
    print("    ██║█████╗  █████╗     ██║      ")
    print("    ██║██╔══╝  ██╔══╝     ██║      ")
    print("    ██║██║     ██║        ██║      ")
    print("    ╚═╝╚═╝     ╚═╝        ╚═╝      ")
    print("\n") 
    print("██████╗          ██╗       ██████╗    ")
    print("██╔══██╗         ╚██╗     ██╔═══██╗   ")
    print("██████╔╝    █████╗╚██╗    ██║   ██║   ")
    print("██╔═══╝     ╚════╝██╔╝    ██║▄▄ ██║   ")
    print("██║              ██╔╝     ╚██████╔╝   ")
    print("╚═╝              ╚═╝       ╚══▀▀═╝    ")
    print("\033[0m")    
    print("\033[1;36m")
    print("   IFFT v1.0")
    print("   Developed by: Thiago Santos")
    print("   GitHub: github.com/thiagosantos0")
    print("\033[0m")    
    print("\n")

def main_menu():    
    print("1. Run")    
    print("2. Change Pattern")    
    print("3. Exit")    
    print("\n")    
    
if __name__ == "__main__":    
    banner()    
    main_menu()
