site_name: IFFT Tool Documentation

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature: true
            show_source: true

nav:
  - Home: index.md
  - IFFT Modes:
    - Example - Manual: tutorial-example-manual.md
    - Example - Automode: 'tutorial-example-automode.md'
    - Interface Web: 'tutorial-example-interface.md'
  - Reference:
    - Parser: reference.md # ifft_core
    - Block Manager Class: block_manager.md
    - Helpers: helpers.md
