site_name: My Docs

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings

nav:
  - index.md
  - Automode config: configuration.md
  - Example - Manual: tutorial-example-manual.md
  - Example - Automode: 'tutorial-example-automode.md'
  - reference.md
