site_name: My Docs

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings

nav:
  - index.md
  - Tutorial: 'tutorial-example.md'
  - reference.md
